name:use workflow1
on: push
jobs:
  jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - run: workflow1.yml
    job2:
      runs-on: ubuntu-latest
      steps:
        - run: echo "workflow1 success"
      needs: job1


